remote_theme: just-the-docs/just-the-docs
logo: "images/Fismology.png"
aux_links:
  "Docs":
    - "//docs.fismo.xyz"
  "NPM":
    - "//www.npmjs.com/package/fismo"
  "GitHub":
    - "//github.com/cliffhall/Fismology"
  "Discord":
    - "//discord.gg/eAkBctf3Pc"
  "Twitter":
    - "//twitter.com/FismoProtocol"
